language: python
python:
- "3.6"
env:
  global:
  - AWS_DEFAULT_REGION=us-east-1
  - AWS_ACCESS_KEY_ID=AKIAIZNCSSQ3OUSAT25A
  - secure: "WuEBhkC1WtdkbyDX4Mw3x1JwcglAXQi0NQ1fnEBxYOzmvANfNktluR0udHwTx+k4p7XpCs7XvTpb10ihX0FDve7qPTYAGRBet4jUfZvDz7ZgEcTFDrIVZOm7nCGFQ1GffY4BcOPr0VdxmRFWGlU7qfTqwF2NEY3U4tpeh0Z4XOxZ1wnyig9pwcPOp92A5wFdFkfF3UtjIl1sOZTE/cGAmgJufTzz7EVqtz9x37OnrGyQl67ZBW5w+BSTWrK3nGaHqhloDx3QrfqO1Ny6SWKqjch5MU4l0G5zndz5ZyPMywRB2LS6DRaeKqT9v1ltD09U9Z2UvMSF5G+tW5SJqFpcHuSfSG/LLUtoUWLykVULOsK+cQOkp0Lb32XJCyCnFV0OLinfNYp1nhY7mI9+u7h8T6mC2c/CReRKQ97V1Encd7phTUy6H2ah6QDpHRFLhgLQz2Oym4Y9vGhQ2VqUmE+hiUyy8qDY6wQjkdoDQf7qPLJQufCkHD9lYHYWhKK9cs059Iit+c70Y9QAVYwUw0Twxs714v04ORRE0fctY/bbIOZ8dI57gKSjcZPjT3GLphbg/+GD8qMZVfEh7OdFOnaRjmkr2+RZ1XdChlPYaPFcfgRv98n7zvvuxNXTKjtDSKslEAXP29Vz0QY3otUA5pPFogCmtuN9LApq1R6DjEfRHs4="
  matrix:
  - DISTRO=amazon-linux
  - DISTRO=ubuntu-trusty
  - DISTRO=ubuntu-xenial
  - DISTRO=ubuntu-bionic
  - DISTRO=debian-jessie
  - DISTRO=debian-stretch
install:
- pip install awscli
script:
- make ${DISTRO}
